// Character Sheet Feature - Public API
export { useCharacterSheet } from "./hooks/useCharacterSheet";
export { useReferenceData } from "./hooks/useReferenceData";
export {
  getAttributeDice,
  getTotalXP,
  createDefaultCharacter,
  countActionDots,
  computeActionDotBudget,
  viceOptions,
  standardAbilities,
  traumaObjectToIds,
  resolveHeritagePkForSave,
  resolveCharacterCampaignContext,
  isUserCampaignGmForCharacter,
  isGmViewingPlayerCharacterSheet,
  isUserGmOfCharacterCampaign,
  isStandCoinChargenEditable,
  sheetCustomAbilityContentScore,
  mergeAbilitiesPreferRicherCustoms,
  mergeServerOwnedCharacterFields,
  playbookAbilityRequiredLevel,
  isSpinFoundationAbility,
  isHamonFoundationAbility,
  isPlaybookFoundationAbility,
  playbookFoundationAbilities,
  mergePlaybookFoundationAbilities,
  abilitiesMissingPlaybookFoundations,
  playbookGateLevel,
  playbookAbilityLevelMet,
  playbookAbilityRequirementLabel,
  countCombinedNonFoundationPlaybookAbilities,
  playbookAbilitySlotBudget,
  canAddNonFoundationPlaybookAbility,
  computePcLevelFromSheet,
  shouldSkipServerOwnedFieldHydration,
  SERVER_OWNED_FIELD_TOUCH_KEYS,
  computeHealingClockAfterSegments,
  normalizeCrewFromCharacter,
  resolveCrewFromCampaign,
} from "./utils/characterUtils";
export * from "./services/api";
