#!/usr/bin/env bash
set -euo pipefail

echo "Manual Release Signoff"
echo "======================"
echo ""
echo "Owner must verify each item and capture evidence (screenshot or log snippet)."
echo ""
echo "[Auth]"
echo "1. Signup, login, logout path works."
echo "2. Protected pages redirect unauthenticated users."
echo ""
echo "[Character lifecycle]"
echo "3. Create character, edit fields, refresh page, values persist."
echo "4. Delete character and verify it no longer appears in list."
echo ""
echo "[Session roll loop]"
echo "5. GM starts session with default position/effect."
echo "6. Player submits roll-action linked to active session."
echo "7. GM sees roll history and can patch position/effect."
echo ""
echo "[Performance baseline]"
echo "8. API latency check passes budget."
echo "9. Lighthouse check passes budget."
echo ""
echo "Use scripts/perf outputs as release evidence."
