# Generated by Django 5.2 on 2025-07-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_type', models.CharField(choices=[('ACTION', 'Action Roll'), ('RESISTANCE', 'Resistance Roll'), ('FORTUNE', 'Fortune Roll'), ('CLEAR_STRESS', 'Clear Stress Roll'), ('OTHER', 'Other')], max_length=20)),
                ('action_type', models.CharField(choices=[('SOLO', 'Solo Action'), ('GROUP', 'Group Action'), ('ASSISTED', 'Assisted Action')], default='SOLO', max_length=10)),
                ('dice_pool', models.IntegerField(default=0)),
                ('results', models.JSONField(default=list, help_text='List of individual dice results (e.g., [6, 4, 1])')),
                ('outcome', models.CharField(choices=[('CRITICAL_SUCCESS', 'Critical Success'), ('FULL_SUCCESS', 'Full Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILURE', 'Failure'), ('BOTCH', 'Botch')], max_length=20)),
                ('description', models.TextField(blank=True, help_text="What was the roll for? (e.g., 'Skirmish to attack the guard')")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_rolls', to='characters.character')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='characters.character')),
                ('group_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_group_rolls', to='characters.character')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='characters.session')),
            ],
        ),
        migrations.CreateModel(
            name='RollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_history', to='characters.campaign')),
                ('roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_entry', to='characters.roll')),
            ],
            options={
                'verbose_name_plural': 'Roll histories',
            },
        ),
    ]
