# Generated by Django 5.2 on 2025-05-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='hp_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='action_dots',
            field=models.JSONField(choices=[('STAND', 'Stand'), ('HAMON', 'Hamon'), ('SPIN', 'Spin')], default='STAND', max_length=20),
        ),
    ]
