# Generated by Django 5.2 on 2025-05-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_ability_hp_cost_alter_character_action_dots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='special_ability',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='unique_ability',
        ),
        migrations.AddField(
            model_name='ability',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('stand', 'Stand')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='stand',
            name='armor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='action_dots',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stand',
            name='standard_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stand_default', to='characters.ability'),
        ),
        migrations.CreateModel(
            name='StandAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='characters.stand')),
            ],
        ),
    ]
