# Generated by Django 5.2.4 on 2025-07-12 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_roll_rollhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CrewSpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rollhistory',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='rollhistory',
            name='campaign',
        ),
        migrations.RenameField(
            model_name='crew',
            old_name='tier',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='crew_upgrades',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='favored_operations',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='personalization_questions',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='starting_upgrades',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='upgrades',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='xp_trigger',
        ),
        migrations.AddField(
            model_name='crew',
            name='advancement_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crew',
            name='upgrade_progress',
            field=models.JSONField(default=dict, help_text="Progress on crew upgrades, e.g., {'Smuggling Tunnels': 2}"),
        ),
        migrations.AddField(
            model_name='crew',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crew',
            name='xp_track_size',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='faction',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='proposed_score_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='proposed_score_target',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='crew',
            name='claims',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='special_abilities',
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='characters.campaign')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_chat_messages', to='characters.session')),
            ],
        ),
        migrations.CreateModel(
            name='CrewPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('claims', models.ManyToManyField(related_name='playbooks', to='characters.claim')),
                ('special_abilities', models.ManyToManyField(related_name='playbooks', to='characters.crewspecialability')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.crewplaybook'),
        ),
        migrations.CreateModel(
            name='CrewUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_boxes', models.IntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Change in stress (positive for gain, negative for relief)')),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_history', to='characters.character')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_stress_history', to='characters.session')),
            ],
        ),
        migrations.CreateModel(
            name='XPHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_history', to='characters.character')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_xp_history', to='characters.session')),
            ],
        ),
        migrations.DeleteModel(
            name='Roll',
        ),
        migrations.DeleteModel(
            name='RollHistory',
        ),
        migrations.AddField(
            model_name='crew',
            name='claims',
            field=models.ManyToManyField(blank=True, related_name='crews', to='characters.claim'),
        ),
        migrations.AddField(
            model_name='crew',
            name='special_abilities',
            field=models.ManyToManyField(blank=True, related_name='crews', to='characters.crewspecialability'),
        ),
    ]
