# Generated by Django 5.2.4 on 2025-07-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_add_level_to_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='harm_clock_max',
            field=models.IntegerField(default=4),
        ),
    ]
