# Generated by Django 5.2 on 2025-05-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_character_special_ability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='hp_cost',
        ),
        migrations.AddField(
            model_name='character',
            name='custom_ability_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='custom_ability_type',
            field=models.CharField(choices=[('single_with_3_uses', 'Single Ability with 3 Uses'), ('three_separate_uses', 'Three Separate Abilities')], default='single_with_3_uses', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='extra_custom_abilities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='standard_abilities',
            field=models.ManyToManyField(blank=True, related_name='characters_standard', to='characters.ability'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stand',
            name='type',
            field=models.CharField(choices=[('COLONY', 'Colony Stand'), ('TOOLBOUND', 'Tool Bound'), ('PHENOMENA', 'Phenomena'), ('AUTOMATIC', 'Automatic'), ('FIGHTING', 'Fighting Spirit')], max_length=30),
        ),
    ]
