# Generated by Django 5.2 on 2025-06-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_hamonability_spinability_downtimeactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trauma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='crew',
            name='heat',
        ),
        migrations.AddField(
            model_name='campaign',
            name='wanted_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='faction_reputation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='gm_allowed_edit_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='gm_character_locked',
            field=models.BooleanField(default=False),
        ),
    ]
