# Generated by Django 5.2 on 2026-02-25 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_faction_faction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='category',
            field=models.CharField(choices=[('aggression', 'Aggression'), ('endurance', 'Endurance'), ('cunning', 'Cunning'), ('awareness', 'Awareness'), ('presence', 'Presence'), ('teamwork', 'Teamwork'), ('adaptability', 'Adaptability'), ('stand_nature', 'Stand Nature')], default='aggression', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='coin_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='character',
            name='trauma',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='vice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.vice'),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp_clocks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
