# Generated by Django 5.2 on 2025-07-21 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_faction_faction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_stand_coin_points', models.IntegerField(default=10, help_text='Total Stand Coin points for level 1 characters')),
                ('level_1_action_dice', models.IntegerField(default=7, help_text='Total action dice for level 1 characters')),
                ('max_dice_per_action', models.IntegerField(default=4, help_text='Maximum dice per action rating')),
                ('max_dice_per_action_level_1', models.IntegerField(default=2, help_text='Maximum dice per action at level 1')),
                ('stand_coin_stat_properties', models.JSONField(default=dict, help_text='Properties for each Stand Coin stat grade')),
                ('stress_rules', models.JSONField(default=dict, help_text='Stress rules and modifications')),
                ('is_global', models.BooleanField(default=True, help_text='If True, these are global rules. If False, campaign-specific.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_rules', to='characters.campaign')),
            ],
            options={
                'verbose_name_plural': 'Game Rules',
                'unique_together': {('campaign', 'is_global')},
            },
        ),
    ]
