# Generated by Django 5.2 on 2025-07-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_gamerules'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerules',
            name='ability_rules',
            field=models.JSONField(default=dict, help_text='Rules for abilities gained from A-rank stats and starting abilities'),
        ),
        migrations.AddField(
            model_name='gamerules',
            name='default_crew_data',
            field=models.JSONField(default=dict, help_text='Default crew templates and data'),
        ),
        migrations.AddField(
            model_name='gamerules',
            name='default_npc_data',
            field=models.JSONField(default=dict, help_text='Default NPC templates and data'),
        ),
        migrations.AddField(
            model_name='gamerules',
            name='xp_track_rules',
            field=models.JSONField(default=dict, help_text='Default XP tracks and advancement rules'),
        ),
    ]
