# Generated by Django 5.2 on 2026-02-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_add_category_to_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamonability',
            name='required_a_count',
            field=models.IntegerField(default=0, help_text='Minimum number of A-rank Coin stats required (0 for Foundation abilities)'),
        ),
        migrations.AddField(
            model_name='spinability',
            name='required_a_count',
            field=models.IntegerField(default=0, help_text='Minimum number of A-rank Coin stats required (0 for Foundation abilities)'),
        ),
        migrations.AlterField(
            model_name='hamonability',
            name='hamon_type',
            field=models.CharField(choices=[('FOUNDATION', 'Foundations of Hamon'), ('TRADITIONALIST', 'Traditionalist (Zeppeli Style)'), ('ADAPTIVE_FLOW', 'Adaptive Flow (Joseph/Caesar Style)'), ('CYBER_HAMONIST', 'Cyber-Hamonist'), ('DARK_RESONANCE', 'Dark Resonance'), ('BIO_HARMONICS', 'Bio-Harmonics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spinability',
            name='spin_type',
            field=models.CharField(choices=[('FOUNDATION', 'Spin Foundations'), ('CAVALIER', 'Cavalier'), ('EXECUTIONER', 'Executioner'), ('MEDICO', 'Medico'), ('BALLBREAKER', 'Ballbreaker')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stand',
            name='type',
            field=models.CharField(choices=[('COLONY', 'Colony Stand'), ('TOOLBOUND', 'Tool Bound'), ('PHENOMENA', 'Phenomena'), ('AUTOMATIC', 'Automatic'), ('FIGHTING', 'Fighting Spirit'), ('SHARED', 'Shared')], max_length=30),
        ),
    ]
