# Generated by Django 5.2 on 2025-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_playbook_alter_character_playbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='playbook',
            field=models.CharField(choices=[('STAND', 'Stand'), ('HAMON', 'Hamon'), ('SPIN', 'Spin')], default='STAND', max_length=20),
        ),
        migrations.DeleteModel(
            name='Playbook',
        ),
    ]
