# Generated by Django 5.2 on 2025-07-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_gamerules_ability_rules_gamerules_default_crew_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerules',
            name='ability_rules',
        ),
        migrations.RemoveField(
            model_name='gamerules',
            name='default_crew_data',
        ),
        migrations.RemoveField(
            model_name='gamerules',
            name='default_npc_data',
        ),
        migrations.RemoveField(
            model_name='gamerules',
            name='xp_track_rules',
        ),
        migrations.AddField(
            model_name='gamerules',
            name='abilities_per_a_grade',
            field=models.IntegerField(default=2, help_text='Additional abilities gained per A-grade Stand stat'),
        ),
        migrations.AddField(
            model_name='gamerules',
            name='default_starting_abilities',
            field=models.IntegerField(default=3, help_text='Default number of abilities for new characters'),
        ),
        migrations.AddField(
            model_name='gamerules',
            name='default_xp_track_size',
            field=models.IntegerField(default=8, help_text='Default XP track size for all categories'),
        ),
        migrations.AddField(
            model_name='gamerules',
            name='xp_cost_action_dice',
            field=models.IntegerField(default=5, help_text='XP cost per action die gained'),
        ),
        migrations.AddField(
            model_name='gamerules',
            name='xp_cost_heritage_point',
            field=models.IntegerField(default=5, help_text='XP cost per heritage point gained'),
        ),
        migrations.AddField(
            model_name='gamerules',
            name='xp_cost_stand_coin_point',
            field=models.IntegerField(default=10, help_text='XP cost per Stand Coin point gained'),
        ),
        migrations.AddField(
            model_name='gamerules',
            name='xp_track_sizes',
            field=models.JSONField(default=dict, help_text='XP track sizes for different categories'),
        ),
    ]
