# Generated by Django 5.2 on 2025-07-03 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_character_playbook_delete_playbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='stats',
            new_name='relationships',
        ),
        migrations.AddField(
            model_name='npc',
            name='armor_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_npcs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npc',
            name='custom_abilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='harm_clock_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='harm_clock_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='npc',
            name='heritage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.heritage'),
        ),
        migrations.AddField(
            model_name='npc',
            name='playbook',
            field=models.CharField(choices=[('STAND', 'Stand'), ('HAMON', 'Hamon'), ('SPIN', 'Spin')], default='STAND', max_length=20),
        ),
        migrations.AddField(
            model_name='npc',
            name='precision_grade',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='stand_coin_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='npc',
            name='vulnerability_clock_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='vulnerability_clock_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='npc',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npcs', to='characters.campaign'),
        ),
    ]
