# Generated by Django 5.2 on 2025-07-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_remove_gamerules_ability_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerules',
            name='stand_coin_grade_points',
            field=models.JSONField(default=dict, help_text='Point costs for each Stand Coin grade (S, A, B, C, D, F)'),
        ),
    ]
