# Generated by Django 5.2 on 2025-07-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_rename_stats_npc_relationships_npc_armor_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='harm_clock_max',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='precision_grade',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='vulnerability_clock_max',
        ),
        migrations.AddField(
            model_name='npc',
            name='appearance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='desire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='need',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='passion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='npc',
            name='rumour',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='special_traits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='stand_appearance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='stand_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='stand_manifestation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='weakness',
            field=models.TextField(blank=True),
        ),
    ]
