# Generated by Django 5.2 on 2025-07-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_remove_npc_harm_clock_max_remove_npc_precision_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='npc',
            name='faction_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='npc',
            name='inventory',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='npc',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='npc',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='purveyor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
