# Generated by Django 5.2 on 2026-02-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_character_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_scene_type',
            field=models.CharField(choices=[('NONE', 'None'), ('ENTANGLEMENT', 'Entanglement'), ('ALL_OUT_BRAWL', 'All-Out-Brawl')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='progressclock',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_clocks', to='characters.npc'),
        ),
        migrations.AddField(
            model_name='progressclock',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_clocks', to='characters.session'),
        ),
        migrations.AddField(
            model_name='progressclock',
            name='visible_to_players',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progressclock',
            name='clock_type',
            field=models.CharField(choices=[('DANGER', 'Danger'), ('MISSION', 'Mission'), ('RACING', 'Racing'), ('LINKED', 'Linked'), ('TUG_OF_WAR', 'Tug-of-War'), ('PROJECT', 'Long-term Project'), ('HEALING', 'Healing Clock'), ('NPC_OPPONENT', 'NPC Opponent'), ('COUNTDOWN', 'Countdown Clock'), ('CUSTOM', 'Custom Clock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='progressclock',
            name='max_segments',
            field=models.IntegerField(default=4, help_text='Total number of segments (4, 6, 8, 10, or 12)'),
        ),
        migrations.CreateModel(
            name='ShowcasedNPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveal_items', models.BooleanField(default=False)),
                ('reveal_stand_stats', models.BooleanField(default=False)),
                ('reveal_faction_status', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcased_npcs', to='characters.campaign')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcased_in', to='characters.npc')),
            ],
            options={
                'unique_together': {('campaign', 'npc')},
            },
        ),
    ]
