# Generated by Django 5.2 on 2026-02-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_campaign_session_opposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_type', models.CharField(choices=[('ACTION', 'Action Roll'), ('RESISTANCE', 'Resistance Roll'), ('FORTUNE', 'Fortune Roll'), ('CLEAR_STRESS', 'Clear Stress Roll'), ('OTHER', 'Other')], default='ACTION', max_length=20)),
                ('action_name', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(choices=[('controlled', 'Controlled'), ('risky', 'Risky'), ('desperate', 'Desperate')], default='risky', max_length=20)),
                ('effect', models.CharField(choices=[('limited', 'Limited'), ('standard', 'Standard'), ('greater', 'Greater')], default='standard', max_length=20)),
                ('dice_pool', models.IntegerField(default=0)),
                ('results', models.JSONField(default=list, help_text='List of dice results')),
                ('outcome', models.CharField(choices=[('CRITICAL_SUCCESS', 'Critical Success'), ('FULL_SUCCESS', 'Full Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILURE', 'Failure'), ('BOTCH', 'Botch')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='characters.character')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='characters.session')),
            ],
        ),
        migrations.CreateModel(
            name='RollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_history', to='characters.campaign')),
                ('roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_entry', to='characters.roll')),
            ],
            options={
                'verbose_name_plural': 'Roll histories',
            },
        ),
    ]
