# Generated by Django 5.2 on 2025-07-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_npc_contacts_npc_faction_status_npc_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
