# Generated by Django 5.2 on 2025-07-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_character_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='action_dice_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='heritage_points_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='stand_coin_points_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='total_xp_spent',
            field=models.IntegerField(default=0),
        ),
    ]
