# Generated by Django 5.2 on 2026-02-27 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_add_roll_position_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npcs', to='characters.faction'),
        ),
    ]
