# Generated by Django 5.2 on 2025-07-03 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_character_action_dice_gained_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_crew_names', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crew',
            name='proposed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_crew_names', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crew',
            name='proposed_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
