# Generated by Django 5.2 on 2025-07-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_crew_approved_by_crew_proposed_by_crew_proposed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='stand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
