# Generated by Django 5.2 on 2025-07-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_npc_stand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gm_can_have_s_rank_stand_stats',
            field=models.BooleanField(default=False),
        ),
    ]
