# Generated by Django 5.2 on 2025-07-06 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_character_gm_can_have_s_rank_stand_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='development_temporary_ability',
            field=models.JSONField(blank=True, default=None, help_text='Temporary ability gained from A-rank Development Potential until the end of the session', null=True),
        ),
        migrations.CreateModel(
            name='CharacterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_fields', models.JSONField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='characters.character')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
