# Generated by Django 5.2 on 2025-07-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_character_development_temporary_ability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title or name of the session/episode', max_length=200)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Overall plot or story summary for the session')),
                ('factions_involved', models.JSONField(blank=True, default=list, help_text="List of factions involved in the session (e.g., ['The Red Sashes', 'City Watch'])")),
                ('log', models.JSONField(blank=True, default=list, help_text='Chronological log of events: rolls, stress, group actions, etc.')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='characters.campaign')),
                ('characters_involved', models.ManyToManyField(blank=True, related_name='sessions_involved', to='characters.character')),
                ('npcs_involved', models.ManyToManyField(blank=True, related_name='sessions_involved', to='characters.npc')),
            ],
        ),
    ]
