# Generated by Django 5.2 on 2025-07-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencetracker',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_entries', to='characters.session'),
        ),
    ]
