# Generated by Django 5.2 on 2025-07-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_experiencetracker_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='contacts',
            field=models.JSONField(blank=True, default=list, help_text='List of contacts with their details'),
        ),
        migrations.AddField(
            model_name='crew',
            name='crew_upgrades',
            field=models.JSONField(blank=True, default=list, help_text='List of crew-specific upgrades'),
        ),
        migrations.AddField(
            model_name='crew',
            name='favored_operations',
            field=models.JSONField(blank=True, default=list, help_text='List of favored operation types'),
        ),
        migrations.AddField(
            model_name='crew',
            name='personalization_questions',
            field=models.JSONField(blank=True, default=list, help_text='Questions to personalize the crew'),
        ),
        migrations.AddField(
            model_name='crew',
            name='special_abilities',
            field=models.JSONField(blank=True, default=list, help_text='List of crew special abilities'),
        ),
        migrations.AddField(
            model_name='crew',
            name='starting_upgrades',
            field=models.JSONField(blank=True, default=list, help_text='Starting upgrades for the crew'),
        ),
        migrations.AddField(
            model_name='crew',
            name='xp_trigger',
            field=models.TextField(blank=True, help_text='XP trigger for the crew'),
        ),
    ]
