# Generated by Django 5.2 on 2025-07-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_crew_contacts_crew_crew_upgrades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='factions',
            field=models.JSONField(blank=True, default=list, help_text='List of factions and their status within the campaign'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.JSONField(blank=True, default=list, help_text='List of items the character possesses'),
        ),
        migrations.AlterField(
            model_name='downtimeactivity',
            name='activity_type',
            field=models.CharField(choices=[('ACQUIRE_ASSET', 'Acquire Asset'), ('LONG_TERM_PROJECT', 'Long-term Project'), ('RECOVER', 'Recover'), ('REDUCE_HEAT', 'Reduce Heat'), ('TRAIN', 'Train'), ('INDULGE_VICE', 'Indulge Vice'), ('REDUCE_WANTED_LEVEL', 'Reduce Wanted Level')], max_length=20),
        ),
    ]
