# Generated by Django 5.2 on 2025-07-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_campaign_factions_character_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='reputation_status',
            field=models.JSONField(blank=True, default=dict, help_text="Tracks character's reputation with allies, rivals, and factions (e.g., {'Faction Name': 2, 'NPC Name': -1})"),
        ),
    ]
