# Generated by Django 5.2 on 2025-07-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_character_reputation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='factions',
        ),
        migrations.RemoveField(
            model_name='session',
            name='factions_involved',
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faction_type', models.CharField(choices=[('CRIMINAL', 'Criminal'), ('NOBLE', 'Noble'), ('MERCHANT', 'Merchant'), ('POLITICAL', 'Political'), ('RELIGIOUS', 'Religious'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('hold', models.CharField(choices=[('weak', 'Weak'), ('strong', 'Strong')], default='weak', max_length=10)),
                ('reputation', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='characters.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='progressclock',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_clocks', to='characters.faction'),
        ),
        migrations.AddField(
            model_name='session',
            name='factions_involved',
            field=models.ManyToManyField(blank=True, related_name='sessions_involved', to='characters.faction'),
        ),
    ]
