# Generated by Django 5.2 on 2025-07-08 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_remove_campaign_factions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='log',
        ),
        migrations.AddField(
            model_name='campaign',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_campaign', to='characters.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='objective',
            field=models.TextField(blank=True, help_text='The main goal for this session'),
        ),
        migrations.AddField(
            model_name='session',
            name='planned_for_next_session',
            field=models.TextField(blank=True, help_text='Notes for the next session'),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=10),
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DICE_ROLL', 'Dice Roll'), ('STRESS_CHANGE', 'Stress Change'), ('HARM_APPLIED', 'Harm Applied'), ('ITEM_ACQUIRED', 'Item Acquired'), ('DEVILS_BARGAIN', "Devil's Bargain"), ('LOCATION_CHANGE', 'Location Change'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_events', to='characters.character')),
                ('npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_events', to='characters.npc')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='characters.session')),
            ],
        ),
    ]
