# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0058_faction_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional HTTPS URL for crew portrait (no file upload).",
                max_length=500,
            ),
        ),
    ]
