# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0059_crew_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="auto_encoded_xp_settled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When true, encoded session-end XP (vice/playbook hints from rolls) "
                    "was applied once. Entanglement / score conflict XP stays manual."
                ),
            ),
        ),
    ]
