# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0060_session_auto_encoded_xp_settled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencetracker",
            name="trigger",
            field=models.CharField(
                choices=[
                    (
                        "BELIEFS",
                        "Express beliefs, drives, heritage, or background",
                    ),
                    ("STRUGGLE", "Struggle with issues from vice or trauma"),
                    ("DESPERATE", "Address a challenge with action rating 0"),
                    ("DESPERATE_ROLL", "Desperate skill check"),
                    ("STANDOUT", "Standout action or leadership"),
                    ("MANUAL", "Manual or offline XP award"),
                ],
                max_length=24,
            ),
        ),
    ]
