# Generated by Django — Alien Understanding / sheet disguise toggle

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0068_assist_help_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="disguised_as_human",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text=(
                    "When true, Alien Understanding social penalty does not apply "
                    "(disguised as a human)."
                ),
                null=True,
            ),
        ),
    ]
