# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0074_alter_character_disguised_as_human"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="stand_armor_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="has_physical_armor_item",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, this PC tracks a physical armor pool (worn gear / heritage). "
                    "Pool size is `physical_armor_bonus_charges` (GM 0–6 from fiction)."
                ),
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="physical_armor_bonus_charges",
            field=models.IntegerField(
                default=0,
                help_text="Physical armor charge count when has_physical_armor_item (0–6).",
            ),
        ),
    ]
