# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0075_character_stand_and_physical_armor"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="physical_armor_used",
            field=models.IntegerField(
                default=0,
                help_text=(
                    "Spent physical armor charges (0–6); pool size is "
                    "physical_armor_bonus_charges when has_physical_armor_item."
                ),
            ),
        ),
    ]
