# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0076_character_physical_armor_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="unallocated_xp",
            field=models.IntegerField(
                default=0,
                help_text=(
                    "XP in the session bank: granted at session settle (e.g. Stand Development) "
                    "until the player allocates it to insight/prowess/resolve/heritage/playbook."
                ),
            ),
        ),
    ]
