# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0077_character_unallocated_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="session_xp_triggers",
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text=(
                    "Per-session crew XP trigger toggles, shape: "
                    "{ '<session_id>': { 'challenge': bool, 'reputation': bool, "
                    "'goals': bool, 'credited': bool } }. Crew members toggle these "
                    "at end of session (Blades-style: Contend with challenges, "
                    "Bolster reputation, Express goals). Reset implicitly when the "
                    "active session changes — frontend reads the current session's "
                    "row only. Each toggled trigger adds 1 to Crew.xp once when the "
                    "session ends (credited=True prevents double-credit)."
                ),
            ),
        ),
    ]
