# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0078_crew_session_xp_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="session_rep_contributions",
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text=(
                    "Per-session tally of who drove the “Bolster reputation” toggle "
                    "toward crew rep: { '<session_id>': { '<character_id>': int } }. "
                    "Values are applied to Crew.rep (capped) when the session is "
                    "settled alongside crew XP triggers."
                ),
            ),
        ),
    ]
