# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0079_crew_session_rep_contributions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crew",
            name="session_rep_contributions",
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text=(
                    "Per-session rep contribution tallies keyed by character id, e.g. "
                    '{ "<session_id>": { "<character_id>": int } }. Incremented when a '
                    "crew member toggles the reputation trigger false→true (decrement "
                    "on true→false). Summed into Crew.rep when the session is settled."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="crew",
            name="session_xp_triggers",
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text=(
                    "Per-session crew XP trigger toggles. Each session id maps to "
                    "{challenge, reputation, goals, credited}. Toggled triggers are "
                    "credited to Crew.xp once when the active session changes."
                ),
            ),
        ),
    ]
