# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0080_alter_crew_session_rep_contributions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="visible_to_players",
            field=models.BooleanField(
                default=False,
                help_text="When false, crew reputation with this faction is hidden from players until the GM reveals it.",
            ),
        ),
    ]
