# Generated by Django 5.2 on 2026-05-13 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0081_alter_faction_visible_to_players_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencetracker',
            name='award_source',
            field=models.CharField(choices=[('AUTO', 'Automatic (roll/save settlement)'), ('PLAYER', 'Player self-award'), ('GM', 'GM award')], default='AUTO', help_text='Whether this XP came from auto rules, player self-toggle, or GM grant.', max_length=8),
        ),
        migrations.AddField(
            model_name='experiencetracker',
            name='awarded_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered this award. Null for automatic awards (roll/save/session-end settlement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_xp_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencetracker',
            name='clock_key',
            field=models.CharField(blank=True, default='', help_text="xp_clocks key this entry advanced (e.g. 'playbook', 'insight'); empty for entries that did not directly tick a single clock. Used to roll back the matching clock when the entry is deleted.", max_length=16),
        ),
    ]
