# Generated by Django — playbook XP archetypes + PLAYBOOK_SPECIFIC trigger

from django.db import migrations, models


def forwards_standout_to_playbook_specific(apps, schema_editor):
    ExperienceTracker = apps.get_model("characters", "ExperienceTracker")
    ExperienceTracker.objects.filter(trigger="STANDOUT").update(
        trigger="PLAYBOOK_SPECIFIC"
    )


def backwards_playbook_specific_to_standout(apps, schema_editor):
    ExperienceTracker = apps.get_model("characters", "ExperienceTracker")
    ExperienceTracker.objects.filter(trigger="PLAYBOOK_SPECIFIC").update(
        trigger="STANDOUT"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0083_rename_manual_toggle_to_session_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="playbook_xp_archetypes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="SRD playbook-specific XP archetype keys (multi-select). "
                "Stand: Stand.TYPE_CHOICES; Hamon/Spin: non-FOUNDATION ability path keys.",
            ),
        ),
        migrations.RunPython(
            forwards_standout_to_playbook_specific,
            backwards_playbook_specific_to_standout,
        ),
        migrations.AlterField(
            model_name="experiencetracker",
            name="trigger",
            field=models.CharField(
                choices=[
                    (
                        "BELIEFS",
                        "Express beliefs, drives, heritage, or background",
                    ),
                    ("STRUGGLE", "Struggle with issues from vice or trauma"),
                    ("DESPERATE", "Address a challenge with action rating 0"),
                    ("DESPERATE_ROLL", "Desperate skill check"),
                    (
                        "PLAYBOOK_SPECIFIC",
                        "Playbook-specific XP (end of session)",
                    ),
                    ("MANUAL", "Manual or offline XP award"),
                ],
                max_length=24,
            ),
        ),
    ]
