# Generated by Django 5.2 on 2026-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0086_character_xp_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='selected_benefits',
            field=models.ManyToManyField(blank=True, related_name='npcs', to='characters.benefit'),
        ),
        migrations.AddField(
            model_name='npc',
            name='selected_detriments',
            field=models.ManyToManyField(blank=True, related_name='npcs', to='characters.detriment'),
        ),
    ]
