# Generated by Django 5.2 on 2026-08-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0087_npc_selected_heritage_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='forms',
            field=models.JSONField(blank=True, default=list, help_text='One or more form labels (FORM_CHOICES presets and/or custom strings).'),
        ),
        migrations.AddField(
            model_name='stand',
            name='type_custom',
            field=models.CharField(blank=True, default='', help_text='Optional fiction-only subtype label; does not replace TYPE_CHOICES / XP keys.', max_length=100),
        ),
    ]
