# Generated by Django 5.2 on 2026-08-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0088_stand_forms_type_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterxpallocation',
            name='allocation_type',
            field=models.CharField(choices=[('LEVEL_UP_STAT', 'Level up — Stand Coin stat'), ('LEVEL_UP_DOTS', 'Level up — action dots'), ('LEVEL_UP_HERITAGE', 'Level up — heritage ability'), ('MINOR_ADVANCE', 'Minor advance — action dot'), ('BUY_HP', 'Buy +1 HP with XP')], max_length=32),
        ),
    ]
