# Generated by Django 5.2 on 2026-08-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0092_experiencetracker_innate_trigger'),
        ('characters', '0092_unlock_second_playbook_allocation'),
    ]

    operations = [
    ]
