# Generated by Django 5.2 on 2026-08-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0094_hamon_style_choices_srd'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hamon_armor_used',
            field=models.IntegerField(default=0, help_text='Hamon Armor charges used this score (max 3 for Hamon path).'),
        ),
        migrations.AddField(
            model_name='character',
            name='spin_armor_used',
            field=models.IntegerField(default=0, help_text='Spin Armor charges used this score (max 3 for Spin path).'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='type',
            field=models.CharField(choices=[('COLONY', 'Colony Stand'), ('TOOLBOUND', 'Tool Bound'), ('PHENOMENA', 'Phenomena'), ('AUTOMATIC', 'Automatic'), ('FIGHTING', 'Fighting Spirit'), ('SHARED', 'Shared'), ('CONJOINED', 'Conjoined')], max_length=30),
        ),
    ]
