# Generated by Django 5.2 on 2026-09-04 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0109_sync_srd_equipment_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancementPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('insight', 'Insight'), ('prowess', 'Prowess'), ('resolve', 'Resolve'), ('heritage', 'Heritage'), ('playbook', 'Playbook')], max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('action_dot', 'Action dot'), ('coin_grade', 'Coin grade'), ('ability', 'Ability'), ('acquire_stand', 'Acquire Stand')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('blocked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('applied', 'Applied')], db_index=True, default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='characters.characterxpallocation')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advancement_plan_items', to='characters.character')),
            ],
            options={
                'ordering': ['track', 'order', 'id'],
                'indexes': [models.Index(fields=['character', 'track', 'status', 'order'], name='plan_item_char_track_ord')],
            },
        ),
    ]
